# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robotic_arm_controller
    - gripper_controller

  robotic_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_waist_joint
      - waist_link1_joint
      - link1_link2_joint
      - link2_gipper_base_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: GripperCommand
    joints:
      - right_gripper_joint
    action_ns: gripper_cmd
    default: true