# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robotic_arm_jtc:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robotic_arm_jtc:
  ros__parameters:
    joints:
      - base_waist_joint
      - waist_link1_joint
      - link1_link2_joint
      - link2_gipper_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: right_gripper_joint